pipeline {
    agent any

    environment {
        GOOGLE_CREDENTIALS = credentials('gcp-service-account')
        PROJECT_ID = '<gcp-project-id>'
        REGION = 'us-central1'
        GIT_REPO = 'https://github.com/navdeepz/gcp-helloworld.git'  
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: ${GIT_REPO}]]])
            }
        }
        stage('Setup Terraform') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform apply -auto-approve -var="project_id=$PROJECT_ID" -var="region=$REGION"'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
