apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db_host: {{ .Values.env.DB_HOST | b64enc }}
  db_user: {{ .Values.env.DB_USER | b64enc }}
  db_password: {{ .Values.env.DB_PASSWORD | b64enc }}
